### PR TITLE
Bottom section

### PR DESCRIPTION
**Pull request by jotosound**
Added markup and styles for bottom section.

### CODE REVIEW

**Review by jotosound — COMMENTED** [review]
f

**Review by jotosound — COMMENTED** [review]
Fixed

**Review by jotosound — COMMENTED** [review]
One more time...

**Comment by jkettmann** [comment]
@jotosound Congrats on finishing this job. I'm curious about how you liked it. It seems like everything went fine but you struggled a bit with the conflicts. Is that right?

**Comment by jotosound** [comment]
Yeah got a little hung up at the end, but I persevered! Been a musician most of my life, so looking for all the training I can get to switch over to something more stable. I l knew some git, but it made branching/merging make more sense to me. 
Great Job!

**Comment by jkettmann** [comment]
Thanks a lot for the feedback :smile:

**Pull request merged**
